// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJBqMTW6IIUkdXADpl5jSUf93hT7gxuHo',
    appId: '1:395730239998:web:ac9aa992fc832560b300af',
    messagingSenderId: '395730239998',
    projectId: 'testapp-229bb',
    authDomain: 'testapp-229bb.firebaseapp.com',
    storageBucket: 'testapp-229bb.appspot.com',
    measurementId: 'G-LHGDTP87D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlB6o5jheMygCXGIdw2xgsWnqBHPH4aPs',
    appId: '1:395730239998:android:1b9a6b5a8c2806e9b300af',
    messagingSenderId: '395730239998',
    projectId: 'testapp-229bb',
    storageBucket: 'testapp-229bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgoxm8fYQ-SHfnlzC0C-QiI-3SX0gEt6E',
    appId: '1:395730239998:ios:441dd105bc6c86e2b300af',
    messagingSenderId: '395730239998',
    projectId: 'testapp-229bb',
    storageBucket: 'testapp-229bb.appspot.com',
    iosClientId: '395730239998-utj9ko0cthq7dk0s84meu2l7pvk3bak3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgoxm8fYQ-SHfnlzC0C-QiI-3SX0gEt6E',
    appId: '1:395730239998:ios:441dd105bc6c86e2b300af',
    messagingSenderId: '395730239998',
    projectId: 'testapp-229bb',
    storageBucket: 'testapp-229bb.appspot.com',
    iosClientId: '395730239998-utj9ko0cthq7dk0s84meu2l7pvk3bak3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
